<?xml version="1.0" encoding="utf-8"?><Database Name="sms" Class="MyDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=sms;Integrated Security=True" SettingsObjectName="SchoolMS.Properties.Settings" SettingsPropertyName="smsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.roles" Member="roles">
    <Type Name="role">
      <Column Name="r_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="r_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="r_status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.st_InsertRoles" Method="st_InsertRoles">
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="status" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
</Database>